//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Glanda.rc
//
#define IDC_BTN_RENAME                  3
#define IDR_PREVIEW                     4
#define IDC_BTN_DELETE                  4
#define IDP_OLE_INIT_FAILED             100
#define IDS_COLOR_TRANS_STYLE           101
#define IDS_LIST_CHAR_POS               102
#define IDD_TESTIMPORT_DIALOG           102
#define IDB_BRUSH_SPLITTER              102
#define IDS_FAILED_LAUNCH_HELP          103
#define IDD_NEW_FOLDER                  103
#define IDD_DIRECTORY_PICKER            104
#define IDB_BUTTON_CONSTRAIN            104
#define IDS_TIP_TEXT_TYPE               104
#define IDC_HAND_POINT                  104
#define IDS_OPTIONS                     105
#define IDS_WARNING_VALIDNAME           106
#define IDB_LAME                        106
#define IDS_LIST_TEXTTYPE               107
#define IDD_PUBLISH_SELECT              107
#define IDS_TIP_TEXT_FONT               108
#define IDS_TIP_TEXT_FONT_SIZE          109
#define IDS_TIP_TEXT_CHAR_SPACING       110
#define IDS_PROMPT_SAVE_FILE            111
#define IDS_ENTER_BROWSER_NEW_NAME      112
#define IDS_PLEASE_SELECT_TEMPLATE      113
#define IDS_DEFAULT_FONT_LIST           114
#define IDS_E_INTEGER_OUT_OF_RANGE2     115
#define IDS_E_NUMBER_INVALID1           116
#define IDS_E_FLOAT_OUT_OF_RANGE2       117
#define IDS_E_FLOAT_EMPTY2              118
#define IDS_E_INTEGER_EMPTY2            119
#define IDS_TIP_TEXT_CHAR_POS           120
#define IDS_TIP_TEXT_INDENT             121
#define IDS_TIP_TEXT_LINE_SPACING       122
#define IDS_TIP_TEXT_LEFT_MARGIN        123
#define IDS_LIST_FILL_STYLE             124
#define IDS_TIP_TEXT_RIGHT_MARGIN       125
#define IDS_LIST_SCALETYPE              126
#define IDS_LIST_ROTATETYPE             127
#define IDR_MAINFRAME                   128
#define IDR_PLAYER                      129
#define IDI_PREVIEW                     129
#define IDS_PUBLISH_HTML_OPTIONS        129
#define IDS_RESERROR                    130
#define IDI_BROWSER                     130
#define IDD_EXPORT                      130
#define IDR_TOOLBAR_CUSTOMIZE           131
#define IDS_LIST_TARGET                 131
#define IDS_LIST_CXFORMTYPE             132
#define IDI_OTHER_BROWSER               132
#define IDB_BROKEN_EDGE                 133
#define IDS_LIST_MOVETYPE               133
#define IDI_BUTTON                      133
#define IDS_PUBLISH                     134
#define IDI_SHAPE                       134
#define IDS_PUBLISH_SELECT              135
#define IDI_MOVIECLIP                   135
#define IDS_PUBLISH_EXPORT_MOVIE        136
#define IDI_TEXT                        136
#define IDC_PICKER                      137
#define IDS_PUBLISH_FINISHED            137
#define IDI_GROUP                       137
#define IDS_PUBLISH_INSERT_CODE         138
#define IDC_NO_DROP                     139
#define IDS_PUBLISH_VIEW_CODE           139
#define IDC_DRAG_SINGLE                 140
#define IDS_PUBLISH_SELECT_FILE         140
#define IDC_MY_HAND                     141
#define IDS_LIST_FLASH_QUALITY          141
#define IDS_LIST_FLASH_WMODE            142
#define IDS_LIST_FLASH_SCALE            143
#define IDS_LIST_FLASH_HTML_ALIGN       144
#define IDS_LIST_FLASH_FLASH_ALIGN      145
#define IDD_BROWSER_ADD                 146
#define IDS_PUBLISH_SELECT_HTML         146
#define ID_PREVIEW_IN_DEFAULT_BROWSER   147
#define IDS_LIST_PREVIEW_DIR            148
#define ID_PREVIEW_EDIT_BROWSER_LIST    149
#define IDS_TIP_TEXT_VARIABLE           150
#define IDS_LIST_MULTITYPE              151
#define IDS_PROMPT_EDIT_AS20            152
#define ID_FILE_SAVE_AS_TEMPLATE        153
#define IDS_MB_OK                       154
#define IDS_MB_CANCEL                   155
#define IDS_MB_ABORT                    156
#define IDD_ABOUT_LAME                  156
#define IDS_MB_RETRY                    157
#define IDS_MB_IGNORE                   158
#define IDS_MB_YES                      159
#define IDS_MB_NO                       160
#define IDS_STH_COPY1                   161
#define IDS_STH_COPY_N2                 162
#define IDS_LAYER_N1                    163
#define IDS_PROMPT_COMMAND_ERROR2       164
#define IDS_TIP_GROUP_INSTANCE1         165
#define IDS_TIP_INPUT_TEXT_HERE         166
#define ID_HELP_HELPTOPIC               167
#define ID_HELP_CHECKFORUPDATES         168
#define IDS_TIP_MC_INSTANCE1            169
#define IDS_TIP_BUTTON_INSTANCE1        170
#define IDS_TIP_SHAPE_INSTANCE1         171
#define IDS_ERROR_PASTE_SYMBOL_INSIDE_ITSELF1 172
#define IDS_E_CREATE_TEMP_FILE          173
#define IDS_E_GET_CLIPBOARD_DATA        174
#define IDS_E_CLIPBOARD_FORMAT          175
#define IDS_E_WRITE_TEMP_FILE           176
#define IDS_PROMPT_DRAW_STREAM_SOUND_LAYER 177
#define IDS_PROMPT_DRAW_LOCKED_INVISIBLE_LAYER 178
#define IDS_PROMPT_DRAW_NO_FRAME        179
#define IDS_PROMPT_ENTER_SYMBOL_NAME    180
#define IDS_CANNOT_DELETE_IMAGE1        181
#define IDS_CANNOT_DELETE_SYMBOL1       182
#define IDR_POPUP_NEW                   183
#define IDS_FILE_NOT_EXIST1             183
#define IDR_POPUP_PREVIEW               184
#define IDS_PROMPT_TARGET_REQUIRE_INSTANCE_NAME 184
#define IDS_PROMPT_PATH_REQUIRE_INSTANCE_NAME 185
#define IDR_POPUP_MRU                   186
#define IDS_COLS_INSTANCE               186
#define IDS_MAIN_MOVIE                  187
#define IDS_COLS_SOUND_FRAMES           188
#define IDS_PROMPT_SOUND_NO_FRAME_USED  189
#define IDS_SYMBOL                      190
#define IDS_ERROR_EXPORT_COMPILE_AS     191
#define IDS_PROMPT_NO_ASSOCIATED_SHAPE  192
#define IDS_EXPORT_MOVIE_TITLE          193
#define IDS_EXPORT_MOVIE_PROMPT         194
#define IDS_SYMBOL_NAME1                195
#define IDS_AS_ERROR_INITCLIP1          196
#define IDB_BUTTON_CLOSE                197
#define IDS_AS_ERROR_FRAME3             197
#define IDB_BUTTON_CLOSE_HIGHLIGHT      198
#define IDS_AS_ERROR_INSTANCE_NO_NAME4  198
#define IDS_ERROR_LOAD_COMPILER         199
#define IDS_URL                         200
#define IDS_ORDER_URL                   201
#define IDS_ERROR_INIT_RICHEDIT20       202
#define IDS_SUPPORT_URL                 203
#define IDS_PROMPT_OPEN_FILE2           204
#define IDS_PROMPT_INVALID_SQF1         205
#define IDS_PROMPT_OPEN_HIGHER_VERSION3 206
#define IDS_ERROR_CREATE_TEMP_FILE      207
#define IDR_GLANDA                      208
#define IDS_PAGE_COMMON                 208
#define IDS_ERROR_SAVE_DOCUMENT1        209
#define IDS_ERROR_SAVE_FILE_PERMISSION1 210
#define IDS_FILTER_SWF                  211
#define IDS_PROMPT_FAST_EXPORT          212
#define IDS_IMPORT_TITLE                213
#define IDS_FILTER_ALL                  214
#define IDS_ERROR_UNKNOWN_EXTENSION     215
#define IDS_ERROR_SWF_FORMAT1           216
#define IDS_PROMPT_HIGHER_SWF_VERSION1  217
#define IDS_PROMPT_PROTECTED_SWF        218
#define IDS_ERROR_IMPORT                219
#define IDS_IMPORT_PROMPT               220
#define IDS_ERROR_IMPORT1               221
#define IDS_IMPORT_IMAGE_TITLE          222
#define IDS_FILTER_IMAGE_ALL            223
#define IDS_ERROR_READONLY_FILE1        224
#define IDS_ERROR_CREATE_MOTION_IN_STREAM_SOUND_LAYER 225
#define IDS_MENU_CREATE_MOTION          226
#define IDS_MENU_REMOVE_MOTION          227
#define IDD_COLOR_ADVANCED              228
#define IDS_ERROR_DELETE_STREAM_SOUND_LAYER 228
#define IDS_RENAME_TITLE                229
#define IDS_RENAME_PROMPT               230
#define IDS_TIP_IMAGE_LIST4             231
#define IDS_FRAME_LABEL                 232
#define IDS_FOLDER_N1                   233
#define IDS_ERROR_CREATE_INSTANCE_INSIDE_SELF1 234
#define IDB_ITALIC                      235
#define IDS_ERROR_DELETE_FOLDER_NOT_EMPTY 235
#define IDS_PROMPT_NO_DEFAULT_PLAYER    236
#define IDS_ERROR_SHELLEXECUTE2         237
#define IDS_AS_FOR_INSTANCE1            238
#define IDS_AS_FOR_SYMBOL1              239
#define IDR_UNDO                        240
#define IDS_AS_FOR_FRAME1               240
#define IDS_AS_INITCLIP_FOR_SYMBOL1     241
#define IDS_FRAME_N1                    242
#define IDS_FRAME_N_NAME2               243
#define IDS_ERROR_DELETE_REG_KEY1       244
#define IDS_PROMPT_ENTER_MOVIE_PATH     245
#define IDS_ERROR_INVALID_FILE_PATH1    246
#define IDS_PROMPT_SAVE_MODIFIED_FILE   247
#define IDS_PROMPT_CODE_NOT_INSERTED    248
#define IDS_HTML_TITLE                  249
#define IDB_TOOLBAR_BUTTON              250
#define IDS_TELL_ME_MORE                250
#define IDB_INFORMATION_SMALL           251
#define IDS_FILTER_HTML_ALL             251
#define IDS_PROMPT_ENTER_HTML_FULL_PATH 252
#define IDS_TEXT_TOOL_FONT              253
#define IDS_PROMPT_CREATE_FILE1         254
#define IDS_TIP_SELECT_EFFECT           255
#define IDS_TIP_CONFIG_EFFECT           256
#define IDS_AS_TAB_FRAME                257
#define IDS_LIST_SCENE_EVENTS           258
#define IDS_AS_TAB_MOVIE_CLIP           259
#define IDS_AS_TAB_BUTTON               260
#define IDS_AS_TAB_NONE                 261
#define IDS_SELECTION_CANNOT_HAVE_ACTIONS 262
#define IDS_ONLY_MOVIE_CLIP_CAN_HAVE_INITCLIP_ACTIONS 263
#define IDS_AS_NOTHING_TO_DO            264
#define IDS_CHECK_SYNTAX_NO_ERROR       265
#define ID_HELP_VIEW_SAMPLES            266
#define ID_TOOLS_OPTIONS                267
#define IDS_CHECK_SYNTAX_ERRORS_FOUND   268
#define IDS_STATIC_CONFIGURE_EFFECT     269
#define IDS_STATIC_EDIT_SYMBOL          270
#define ID_VIEW_TIMELINE                271
#define IDB_TOOL_SELECT                 272
#define IDS_SYMBOL_TEXT                 272
#define ID_FILE_IMPORT                  273
#define IDS_SYMBOL_SHAPE                274
#define IDS_SYMBOL_GROUP                275
#define IDS_SYMBOL_EFFECT               276
#define IDS_SYMBOL_MOVIE_CLIP           277
#define IDS_SYMBOL_BUTTON               278
#define IDS_SYMBOL_MORPH_SHAPE          279
#define IDS_SYMBOL_MIXED                280
#define ID_EDIT_DELETE                  281
#define IDS_FAILED_CREATE_EFFECT_1      282
#define ID_VIEW_MOVIE                   283
#define ID_VIEW_SHAPE                   284
#define IDS_TIP_LINE_WIDTH              285
#define ID_VIEW_RESET_PANE_LOCATIONS    286
#define IDS_INVALID_DOCUMENT_1          287
#define IDS_DOCUMENT_VERSION_HIGHER_1   288
#define IDS_TIP_RED                     289
#define IDS_FAILED_OPEN_FILE_1          290
#define IDS_TIP_BLUE                    291
#define ID_INSERT_KEYFRAME              292
#define ID_INSERT_LAYER                 293
#define IDS_TIP_HUE                     294
#define IDS_TIP_SATURATION              295
#define IDS_TIP_VALUE                   296
#define IDS_TIP_ALPHA                   297
#define ID_INSERT_FRAME                 298
#define ID_CREATE_MOTION_TWEEN          299
#define ID_REMOVE_FRAME                 300
#define IDR_DESIGNWND                   300
#define ID_INSERT_BLANKKEYFRAME         301
#define ID_CLEAR_KEYFRAME               302
#define IDS_TIP_LINEAR_GRADIENT_FILL    303
#define IDS_TIP_SV                      304
#define IDS_TIP_COLOR_SAMPLE            305
#define IDS_TIP_HEX                     306
#define IDS_ERROR_CANNOT_DELETE_USED_IMAGE 307
#define IDS_IMPORT_SOUND_TITLE          308
#define ID_CREATE_EFFECT                309
#define IDS_FILTER_SOUND_ALL            310
#define IDS_PROMPT_CHANGE_SOUND_LAYER_LOCKED 311
#define IDS_PROMPT_SOUND_USED_BY_FRAMES1 312
#define IDS_TIP_URL                     313
#define IDS_TIP_TARGET                  314
#define IDB_TOOL_HAND                   315
#define IDS_TIP_TEXT_STYLE              315
#define IDB_TOOL_ZOOM                   316
#define IDS_TIP_TEXT_MAX_CHARS          316
#define IDS_TIP_PEN_TOOL1               317
#define IDS_TIP_PEN_TOOL_TITLE1         318
#define IDS_SOUND_NONE                  319
#define IDS_ERROR_CREATE_SOUND_PREVIEW  320
#define IDS_TIMELINE                    321
#define IDS_TIP_ADD_LAYER               322
#define IDS_FAILED_IMPORT_FILE_1        323
#define IDS_FAILED_INIT_PAGE_1          324
#define IDS_SURE_DEL_TEMPLATE_1         325
#define IDS_FAILED_DEL_TEMPLATE_1       326
#define IDS_TEMPLATE_EXISTS_1           327
#define IDS_ERROR_MOVE_STREAM_SOUND_LAYER 328
#define IDS_ERROR_MOVE_BEFORE_STREAM_SOUND_LAYER 329
#define IDS_FAILED_RENAME_TEMPLATE_1    330
#define IDS_BUTTON_NOT_FOUND_TEXT       331
#define IDS_TIP_GROUP_BEFORE_ADD_EFFECT 332
#define IDS_DONOT_SHOW_AGAIN            333
#define IDS_PROMPT_CHANGE_BUTTON_TEXT   334
#define IDS_PANEL_CAPTION_GREETINGCARD  335
#define IDS_PANEL_CAPTION_PRELOAD       336
#define IDS_PANEL_CAPTION_BACKGROUND    337
#define IDS_FAILED_OPEN_LICENSE_FILE_s  338
#define IDS_FILLSTYLE_d                 339
#define IDS_LINESTYLE_d                 340
#define IDS_SCENE_SOUND_TOOLTIPS_s_d_f_d_f 341
#define IDS_KEY_SCENE                   342
#define IDS_KEY_ELEMENT                 343
#define IDD_CATEGORY_RESOURCE_PAGE      344
#define IDS_COPY_OF_X                   344
#define IDD_CATEGORY_IMPORT_PAGE        345
#define IDS_KEY_UNNAMED                 345
#define IDD_CATEGORY_TOOLS_PAGE         346
#define IDS_N_BYTES                     346
#define IDS_TIP_COLOR_BUTTON            347
#define IDD_CATEGORY_EXPLORER_PAGE      347
#define IDB_TOOL_ZOOMOUT                348
#define IDS_TIP_COLOR_BUTTON_TITLE      348
#define IDB_TOOL_ZOOMIN                 349
#define IDS_FAILED_IMPORT_s             349
#define IDB_TOOL_ANCHORPOINT            350
#define IDS_FAILED_CREATE_DIRECTORY_s   350
#define IDS_AS_ERROR_INSTANCE_WITH_NAME4 351
#define IDB_RESOURCE_DIR_IMAGE_LIST     351
#define IDS_URL_SAMPLES                 352
#define IDB_SLIDING_ARROW               352
#define IDS_MENU_VIEW_INSTANCES         353
#define IDS_MENU_VIEW_SHAPES_FILLED_WITH_IMAGE 354
#define IDS_MENU_EDIT_SYMBOL            355
#define IDS_MENU_CONFIG_EFFECT          356
#define IDS_MENU_EDIT_TEXT              357
#define IDS_MOTION                      358
#define IDB_LAYOUT_ALIGN_CENTER         359
#define IDS_COLS_REPLACE_SYMBOL         359
#define IDB_LAYOUT_ALIGN_LEFT           360
#define IDS_UNDO_ACTION1                360
#define IDB_LAYOUT_ALIGN_RIGHT          361
#define IDS_REDO_ACTION1                361
#define IDS_CSWFLIB_LAYER               362
#define IDB_TOOL_LOCK                   363
#define IDS_CSWFLIB_MASK_LAYER          363
#define IDB_TOOLBAR_TRUECOLOR           364
#define IDS_CSWFLIB_MASKED_LAYER        364
#define IDR_TEXT2                       365
#define IDS_CSWFLIB_DUMMY_LAYER         365
#define IDS_CSWFLIB_ACTION_LAYER        366
#define IDS_CSWFLIB_STREAM_SOUND_LAYER  367
#define IDR_DEBUG                       368
#define IDD_EDIT_GRID                   368
#define IDS_CSWFLIB_EVENT_SOUND_LAYER   368
#define IDS_CSWFLIB_LABEL_LAYER         369
#define IDS_EMPTY_TEXT                  370
#define IDB_PUBLISH_HEADER              371
#define IDS_E_MOVE_UP_FIRST_SCENE       371
#define IDS_COPY_OF_X_N                 372
#define IDR_POPUP_EXPORT_MOVIE          373
#define IDS_PAGE_EFFECT_PREVIEW_OPTIONS 373
#define IDB_MEMBER_LIST                 374
#define IDS_CANT_APPLY_EFFECT           374
#define IDB_BUTTON_MEMBER_LIST          375
#define IDS_TIP_TEXT_INSTANCE1          375
#define IDR_ASVIEW                      376
#define IDS_FIXED_FONT                  376
#define IDR_OUTPUTVIEW                  377
#define IDB_TOOL_LINE_GUIDELINE         377
#define IDS_FIXED_FONT_SIZE             377
#define IDB_TOOL_OVAL_GUIDELINE         378
#define IDS_TIP_TRIAL_WATERMARK         378
#define IDB_TOOL_PEN_GUIDELINE          379
#define IDS_EFFECT_CUSTOM               379
#define IDB_TOOL_PENCIL_GUIDELINE       380
#define IDS_EFFECT_EMPHASIS             380
#define IDB_TOOL_POLYGON_GUIDELINE      381
#define IDR_SCENE                       381
#define IDS_EFFECT_EXIT                 381
#define IDR_RESOURCE_EXPLORER           382
#define IDR_POPUP_RESOURCE_THUMB_ITEM   382
#define IDS_ENTRANCE                    382
#define IDR_TIMELINE                    383
#define IDS_EFFECT_ENTRANCE             383
#define IDR_GLD_APPLICATION             384
#define IDS_BLANK_DOCUMENT              384
#define IDS_CREATE_BLANK_DOCUMENT       385
#define IDB_BUTTON_PARENT_DIR           386
#define IDS_FAILED_INIT_COM             386
#define IDB_BUTTON_HOME_DIR             387
#define IDS_KEY_ACTION                  387
#define IDB_BUTTON_REFRESH_DIR          388
#define IDS_HIDE_ADV_OPTIONS            388
#define IDB_BUTTON_STOCK_RESOURCES      389
#define IDS_SHOW_ADV_OPTIONS            389
#define IDS_EFFECT_MOTION_PATH          390
#define IDB_BUTTON_BACK                 391
#define IDS_EFFECT_SELECT               391
#define IDB_BUTTON_FORWARD              392
#define IDS_RENAME_EFFECT_SETTINGS      392
#define IDB_BUTTON_GOTO_FOLDER          393
#define IDS_INPUT_NEW_SETTINGS_NAME     393
#define IDS_LIST_BACKGROUND_POS         394
#define IDR_POPUP_RESOURCE_TREE         395
#define IDS_MOVIE_PROPERTIES            395
#define IDD_RESOURCE_THUMB_FILE_PROPERTIES 396
#define IDS_SCENE_PROPERTIES            396
#define IDD_RESOURCE_THUMB_RENAME_DIALOG 397
#define IDR_POPUP_RESOURCE_GOTO_FOLDER  397
#define IDS_PREVIEW_OPTIONS             397
#define IDB_EFFWND_BACKGROUND_TILES     398
#define IDS_SAVE_EFFECT_SETTINGS        398
#define IDB_EFFWND_SOUND_TOTAL          399
#define IDS_INPUT_SETTINGS_NAME         399
#define IDS_TOOL_SELECT                 400
#define IDB_EFFWND_SOUND_LINE           400
#define IDS_TOOL_RESHAPE                401
#define IDB_EFFWND_EFFECT_LINE          401
#define IDS_TOOL_LINE                   402
#define IDS_TOOL_PENCIL                 403
#define IDS_TOOL_OVAL                   404
#define IDB_EFFWND_TREE_LINE            404
#define IDS_TOOL_RECT                   405
#define IDS_TOOL_PEN                    406
#define IDS_TOOL_TEXT                   407
#define IDS_TOOL_INK_BOTTLE             408
#define IDS_TOOL_PAINT_BUCKET           409
#define IDD_SELECT_EFFECT               409
#define IDS_TOOL_FILL_TRANSFORM         410
#define IDB_EFFECT_CATS                 411
#define IDS_RELEASE                     411
#define IDS_TOOL_ZOOMOUT                412
#define IDD_IMPORT_IMAGE_DIALOG         412
#define IDS_TOOL_ZOOMIN                 413
#define IDS_TOOL_HAND                   414
#define IDS_TOOL_LOCK                   415
#define IDS_TOOL_ROUND_RECT             416
#define IDS_TOOL_POLYGON                417
#define IDS_TOOL_STAR                   418
#define IDD_PROCESSING                  419
#define IDS_PRESS                       419
#define IDB_HOURGLASS                   420
#define IDS_RELEASEOUTSIDE              420
#define IDR_POPUP_TEXT_STYLE            421
#define IDS_TOOL_PEN_MOTION_PATH        421
#define IDD_PAGE_EFFECT_PREVIEW_OPTIONS 422
#define IDS_ROLLOVER                    422
#define IDR_POPUP_TIME_LINE_SOUND       423
#define IDS_ROLLOUT                     423
#define IDR_POPUP_TIME_LINE_EFFECT      424
#define IDD_PLAY_SOUND_DIALOG           424
#define IDS_DRAGOVER                    424
#define IDD_IMPORTING_SWF               425
#define IDS_DRAGOUT                     425
#define ID_USE_TEXT_TOOL                426
#define IDB_STOCK_RESOURCE_ICON         430
#define IDR_GLM_TRIAL                   433
#define IDB_SPLASH                      434
#define IDB_EFFWND_SOUND_ICON           435
#define IDD_INSERT_TEXT                 436
#define IDB_TTF_BMP                     438
#define IDD_SAVEAS_TEMPLATE             439
#define IDD_APPLY_TEMPLATE              440
#define IDS_NO_ERROR_MSG                442
#define IDS_NO_CURRENT_SCENE            443
#define IDS_REPLACE_EXISTS_TEMPLATE_1   444
#define IDS_FAILED_SAVE_TEMPLATE        445
#define IDB_BITMAP1                     445
#define IDB_COMBO_EFFECT                445
#define IDS_CONTINUE_APPLY_TEMPLATE     446
#define IDD_SELECT_TEXT_CHANGING        446
#define IDS_FAILED_APPLY_TEMPLATE       447
#define IDD_CHANGE_BUTTON_TEXT          447
#define IDS_FAILED_CREATE_PREVIEW       448
#define IDD_SELECT_BACKGROUND_POS       448
#define IDS_NEED_SELECT_ELEMENT         449
#define IDD_SELECT_SCENE                449
#define IDS_NEED_TEXT                   450
#define IDS_NEED_URL                    451
#define IDS_NEED_SELECT_SCENE           452
#define IDS_NEED_SELECT_TEMPLATE        453
#define IDS_INSTALL_FLASH_PLAYER        454
#define IDS_PRERELEASE_EXPIRED          455
#define IDS_PROMPT_PRERELEASE           456
#define IDS_NO_PROMPT_AGAIN             457
#define IDS_FAILED_SET_CLIPBOARD_DATA   458
#define IDS_FAILED_GET_CLIPBOARD_DATA   459
#define IDS_FAILED_SAVE_DOCUMENT        460
#define IDS_FAILED_IMPORT_FILE          461
#define IDS_FAILED_INIT_TEMPLATE        462
#define IDS_CANT_SAVE_ELEMENT           463
#define IDS_FAILED_EXPORT_RESOURCE      464
#define IDS_FAILED_EXPORT_MOVIE         465
#define IDS_NEED_TEMPLATE_NAME          466
#define IDS_FAILED_CREATE_MOTION_PATH   467
#define IDS_SCENE_NAME_EXISTS           468
#define IDS_NEED_SCENE_NAME             469
#define IDC_LIST_FILES                  1000
#define IDC_EDIT_PATH                   1001
#define IDC_STATIC_H                    1002
#define IDC_BUTTON_REFRESH              1002
#define IDC_BUTTON_NEW_FOLDER           1003
#define IDC_STATIC_SV                   1003
#define IDC_BUTTON_START                1003
#define IDC_TREE                        1004
#define IDC_EDIT_H                      1004
#define IDC_BUTTON_SELECTALL            1004
#define IDC_EDIT_S                      1005
#define IDC_EDIT_H_SCALE                1005
#define IDC_CHECK                       1005
#define IDC_BUTTON_DESELECTALL          1005
#define IDC_EDIT_V                      1006
#define IDC_EDIT_B_FACTOR               1006
#define IDC_CHECK_COMPRESS              1006
#define IDC_EDIT_R                      1007
#define IDC_STATIC_TEXT                 1007
#define IDC_EDIT_G                      1008
#define IDC_EDIT_B                      1009
#define IDC_BUTTON_LOCATE               1010
#define IDC_EDIT_Y_SKEW                 1010
#define IDC_LIST                        1011
#define IDC_EDIT_SCALE_H                1011
#define IDC_EDIT_SKEW_Y                 1012
#define IDC_STATIC_SLIDER_H             1016
#define IDC_EDIT_NAME                   1016
#define IDC_EDIT_NEW_FOLDER             1017
#define IDC_STATIC_SLIDER_S             1017
#define IDC_STATIC_SLIDER_V             1018
#define IDC_EDIT_CURENT_FOLDER          1019
#define IDC_STATIC_SLIDER_R             1019
#define IDC_BUTTON_DELETE               1019
#define IDC_STATIC_SLIDER_G             1020
#define IDC_STATIC_SLIDER_B             1021
#define IDC_EDIT_A                      1022
#define IDC_STATIC_SLIDER_LINE_WIDTH    1023
#define IDC_STATIC_SLIDER_A             1024
#define IDC_STATIC_COLOR_OLD            1025
#define IDC_STATIC_COLOR_NEW            1026
#define IDC_LIST_CUSTOMIZED             1026
#define IDC_BUTTON_ADD                  1027
#define IDC_STATIC_SWATCH               1028
#define IDC_BUTTON_UP                   1030
#define IDC_STATIC_R                    1031
#define IDC_STATIC_G                    1032
#define IDC_STATIC_B                    1033
#define IDC_STATIC_LINK                 1033
#define IDC_STATIC_ADVANCED             1034
#define IDC_STATIC_A                    1035
#define IDC_EDIT_LICENSE                1038
#define IDC_EDIT_FILE                   1039
#define IDC_STATIC_URL                  1039
#define IDC_BUTTON_BROWSE               1050
#define IDC_LIST_WELLKNOWN              1053
#define IDC_STATIC_SUPPORT              1053
#define IDC_PROGRESS                    1054
#define IDC_STATIC_WEBSITE              1055
#define IDC_STATIC_PRODUCT              1059
#define IDC_STATIC_WARNING              1060
#define IDC_STATIC_STATUS               1092
#define IDC_STATIC_SPIN_CHAR_SPACING    1099
#define IDC_EDIT_A_FACTOR               1100
#define IDC_STATIC_SPIN_LINE_SPACING    1100
#define IDC_STATIC_SPIN_OFFSET_X        1100
#define IDC_EDIT_INSTANCE_NAME          1101
#define IDC_STATIC_SPIN_INDENT          1101
#define IDC_STATIC_SPIN_OFFSET_Y        1101
#define IDC_STATIC_SPIN_LEFT_MARGIN     1102
#define IDC_STATIC_SPIN_TEXT_WIDTH      1102
#define IDC_STATIC_SPIN_RIGHT_MARGIN    1103
#define IDC_STATIC_SPIN_OFFSET_Y2       1103
#define IDC_STATIC_SPIN_TEXT_HEIGHT     1103
#define IDC_EDIT_HEX                    1106
#define IDC_BUTTON_DOWN                 1116
#define IDC_EDIT_FRAME_RATE             1159
#define IDC_EDIT_LINE_WIDTH             1164
#define IDC_COMBO_FILL_TYPE             1165
#define IDC_BUTTON_LINE_COLOR           1168
#define IDC_BUTTON_BORDER_COLOR         1168
#define IDC_BUTTON_FILL_COLOR           1169
#define IDC_BUTTON_SHADOW_COLOR         1170
#define IDC_BUTTON_TEXT_STYLE1          1171
#define IDC_STATIC_LABEL_H              1172
#define IDC_BUTTON_TEXT_STYLE2          1172
#define IDC_STATIC_LABEL_S              1173
#define IDC_BUTTON_TEXT_STYLE3          1173
#define IDC_STATIC_LABEL_V              1174
#define IDC_BUTTON_TEXT_STYLE4          1174
#define IDC_STATIC_PERCENT_S            1175
#define IDC_BUTTON_TEXT_STYLE5          1175
#define IDC_STATIC_PERCENT_V            1176
#define IDC_BUTTON_TEXT_STYLE6          1176
#define IDC_STATIC_LABEL_R              1177
#define IDC_STATIC_LABEL_G              1178
#define IDC_STATIC_LABEL_B              1179
#define IDC_STATIC_LINEAR_GRADIENT_FILL 1180
#define IDC_BUTTON_BACKGROUND           1181
#define IDC_EDIT_X                      1182
#define IDC_BUTTON_DELETE_IMAGE         1182
#define IDC_BUTTON_TEXT_COLOR           1182
#define IDC_EDIT_Y                      1183
#define IDC_EDIT_COORX                  1183
#define IDC_EDIT_W                      1184
#define IDC_EDIT_COORY                  1184
#define IDC_EDIT_R_FACTOR               1185
#define IDC_EDIT_W_SCALE                1186
#define IDC_BUTTON_CONSTRAIN_SIZE       1187
#define IDC_EDIT_G_FACTOR               1189
#define IDC_EDIT_X_SKEW                 1191
#define IDC_BUTTON_CONSTRAIN_ANGLE      1192
#define IDC_STATIC_DEFREE_X             1195
#define IDC_STATIC_DEFREE_Y             1196
#define IDC_STATIC_DEFREE_ANGLE         1196
#define IDC_BUTTON_COLOR                1199
#define IDC_EDIT_COLOR_FACTOR           1200
#define IDC_STATIC_COLOR_PERCENT        1201
#define IDC_STATIC_SPIN_COLOR_FACTOR    1202
#define IDC_EDIT_ALPHA_FACTOR           1203
#define IDC_STATIC_ALPHA_PERCENT        1204
#define IDC_STATIC_SPIN_ALPHA_FACTOR    1205
#define IDC_STATIC_SPIN_R_FACTOR        1206
#define IDC_STATIC_SPIN_G_FACTOR        1207
#define IDC_STATIC_SPIN_B_FACTOR        1208
#define IDC_STATIC_SPIN_A_FACTOR        1209
#define IDC_STATIC_SPIN_R               1210
#define IDC_STATIC_SPIN_G               1211
#define IDC_STATIC_SPIN_B               1212
#define IDC_STATIC_SPIN_A               1213
#define IDC_STATIC_R1                   1214
#define IDC_STATIC_G1                   1215
#define IDC_STATIC_B1                   1216
#define IDC_STATIC_A1                   1217
#define IDC_STATIC_R2                   1218
#define IDC_STATIC_G2                   1219
#define IDC_STATIC_B2                   1220
#define IDC_STATIC_A2                   1221
#define IDC_STATIC_R3                   1222
#define IDC_STATIC_G3                   1223
#define IDC_STATIC_B3                   1224
#define IDC_STATIC_A3                   1225
#define IDC_CHECK_LOOP                  1227
#define IDC_EDIT_LOOP                   1231
#define IDC_STATIC_SPIN_WIDTH           1234
#define IDC_STATIC_SPIN_HEIGHT          1235
#define IDC_STATIC_SPIN_LOOP            1236
#define IDC_PLAYER                      1237
#define IDC_BUTTON_BOLD                 1240
#define IDC_BUTTON_ITALIC               1241
#define IDC_COMBO_TYPE                  1242
#define IDC_EDIT_TEXT                   1243
#define IDC_BUTTON_ALIGN_CENTER         1243
#define IDC_COMBO_FONT                  1244
#define IDC_EDIT_SIZE                   1245
#define IDC_EDIT_RADIUS                 1246
#define IDC_BUTTON_ALIGN_RIGHT          1246
#define IDC_STATIC_RADIUS               1247
#define IDC_BUTTON_SELECTABLE           1247
#define IDC_STATIC_SPIN_RADIUS          1248
#define IDC_COMBO_CHAR_POS              1248
#define IDC_STATIC_PROMPT               1249
#define IDC_BUTTON_BORDER               1249
#define IDC_COMBO_TARGET                1250
#define IDC_BUTTON_EDITABLE             1251
#define IDC_BUTTON_ALIGN_LEFT           1285
#define IDC_STATIC_CHAR_SPACING         1286
#define IDC_STATIC_SPIN_SIZE            1287
#define IDC_STATIC_SPIN_ANGLE           1287
#define IDC_STATIC_LINE_SPACING         1288
#define IDC_EDIT_LINE_SPACING           1289
#define IDC_SPIN_SHADOW_SIZE            1289
#define IDC_EDIT_CHAR_SPACING           1290
#define IDC_EDIT_INDENT                 1291
#define IDC_EDIT_OFFSET_X               1291
#define IDC_EDIT_LEFT_MARGIN            1292
#define IDC_EDIT_OFFSET_Y               1292
#define IDC_STATIC_INDENT               1293
#define IDC_EDIT_TEXT_WIDTH             1293
#define IDC_STATIC_LEFT_MARGIN          1294
#define IDC_EDIT_TEXT_HEIGHT            1294
#define IDC_EDIT_RIGHT_MARGIN           1295
#define IDC_STATIC_CHAR_POS             1296
#define IDC_STATIC_RIGHT_MARGIN         1297
#define IDC_EDIT_LINK                   1298
#define IDC_STATIC_POINTS               1300
#define IDC_EDIT_POINTS                 1301
#define IDC_STATIC_SPIN_POINTS          1302
#define IDC_CHECK_SHOW_DESIGN_TOOLTIP   1308
#define IDC_CHECK_CENTER_DESIGN_TOOLTIP 1309
#define IDC_CHECK_RELOAD_LAST_DOCUMENT  1309
#define IDC_CHECK_SHOW_CANVAS_BORDER    1310
#define IDC_CHECK_SHOW_NAME             1312
#define IDC_STATIC_ICON                 1318
#define IDC_BUTTON_IMPORT_IMAGE         1319
#define IDC_CHECK_TEST_CHANGE_FRAME     1323
#define IDC_CHECK_TEST_INPLACE_EDIT     1324
#define IDC_STATIC_OPTIONS              1326
#define IDC_BUTTON_BROWSE_SWF_PATH      1328
#define IDC_CHECK_SHOW_BALLOON_TIPS     1328
#define IDC_BUTTON_RESET_ALL_TIPS       1329
#define IDC_BUTTON_EMPTY_CACHE          1330
#define IDC_EDIT_TARGET                 1331
#define IDC_RADIO_RELATIVE              1333
#define IDC_RADIO_ABSOLUTE              1334
#define IDC_CHECK_SHOW_NAMED_ONLY       1335
#define IDC_STATIC_PATH_TYPE            1336
#define IDC_SPIN_LOOP                   1338
#define IDC_BTNCOLOR                    1339
#define IDC_EDTXDIST                    1340
#define IDC_EDTYDIST                    1341
#define IDC_CHKSHOWGRID                 1342
#define IDC_CHKSNAPTOGRID               1343
#define IDC_RADIO_EXPORT_MOVIE          1371
#define IDC_RADIO_VIEW_CODE             1373
#define IDC_RADIO_INSERT_CODE           1374
#define IDC_RICHEDIT_CODE               1374
#define IDC_BUTTON_COPY                 1375
#define IDC_RADIO_WINDOWS               1377
#define IDC_RADIO_UNIX                  1378
#define IDC_RADIO_MAC                   1379
#define IDC_COMBO_FILE                  1380
#define IDC_RICHEDIT_FILE               1381
#define IDC_BUTTON_INSERT               1382
#define IDC_BUTTON_SAVE                 1383
#define IDC_BUTTON_PREVIEW              1384
#define IDC_BUTTON_CHECK_SYNTAX         1387
#define IDC_BUTTON_MEMBER_LIST          1388
#define IDC_BUTTON_PARAMETER_INFO       1389
#define IDC_BUTTON_AUTO_COMPLETE        1390
#define IDC_STATIC_TYPE_IMAGE           1392
#define IDC_EDIT_VARIABLE               1398
#define IDC_STATIC_TYPE_NAME            1400
#define IDC_COMBO_MULTILINE             1421
#define IDC_EDIT_MAXLENGTH              1422
#define IDC_CHECK_INCLUDE_SUB_FOLDERS   1424
#define IDC_CHECK_AUTO_LIST_MEMBERS     1424
#define IDC_CHECK_AUTO_SHOW_PAREMETER_INFO 1425
#define IDC_CHECK_AUTO_INDENT           1426
#define IDC_CHECK_SHOW_SELECTION_MARGIN 1427
#define IDC_CHECK_SHOW_LINE_NUMBERS     1428
#define IDC_STATIC_SPIN_FRAME_RATE      1433
#define IDC_BTN_ADD_EFFECT              1434
#define IDC_BTN_ADD_SOUND               1435
#define IDC_BTN_REMOVE_EFFECT           1439
#define IDC_BTN_REMOVE                  1439
#define IDC_BTN_EFFECT_MOVE_UP          1440
#define IDC_BTN_EFFECT_MOVE_DOWN        1441
#define IDC_BTN_EFFECT_SETTINGS         1442
#define IDC_STATIC_SLIDING_RECT         1444
#define IDC_BTN_EDIT_SHAPE              1447
#define IDC_BTN_EDIT_TEXT               1447
#define IDC_BTN_REPLACE_SHAPE           1448
#define IDC_BTN_REPLACE_SOUND           1448
#define IDC_BUTTON_PLAY_SOUND           1448
#define IDC_BUTTON_CLOSE                1448
#define IDC_BUTTON_APPLY                1449
#define IDC_BTN_REMOVE_SOUND            1449
#define IDC_BUTTON_OPTION               1450
#define IDC_COMBO_URL                   1454
#define IDC_COMBO_SCENES                1455
#define IDC_RADIO_NONE                  1464
#define IDC_RADIO_GET_URL               1465
#define IDC_RADIO_GOTO_SCENE            1466
#define IDC_RADIO_PREV_SCENE            1467
#define IDC_RADIO_NEXT_SCENE            1468
#define IDC_RADIO_PLAY                  1469
#define IDC_RADIO_STOP                  1470
#define IDC_RADIO_CUSTOM                1471
#define IDC_STATIC_SHAPE_PREVIEW        1473
#define IDC_CHECK_AUTO_PLAY             1475
#define IDC_CHECK_PREVIEW_SYNC          1475
#define IDC_CHECK_MASK                  1475
#define IDC_COLOR_TRANS_NONE            1476
#define IDC_CHECK_DONNOT_SHOW_AGAIN     1476
#define IDC_COLOR_TRANS_FADE_TO_ALPHA   1477
#define IDC_COLOR_TRANS_FADE_TO_COLOR   1478
#define IDC_COLOR_TRANS_ADVANCED        1479
#define IDC_LINE_LIST                   1480
#define IDC_CHECK_TILED                 1480
#define IDC_FILL_LIST                   1481
#define IDC_CHECK_SAVE_AS_DEFAULT       1482
#define IDC_STATIC_TARGET               1484
#define IDC_STATIC_ACTIONSCRIPT         1485
#define IDC_EDIT_SCALE_W                1490
#define IDC_EDIT_SKEW_X                 1491
#define IDC_STATIC_LABEL_A              1492
#define IDC_STATIC_PERCENT_A            1493
#define IDC_STATIC_LABEL_X              1494
#define IDC_STATIC_LABEL_Y              1495
#define IDC_STATIC_LABEL_WIDTH          1496
#define IDC_STATIC_LABEL_HEIGHT         1497
#define IDC_STATIC_LABEL_SCALE_W        1498
#define IDC_STATIC_PERCENT_SCALE_W      1499
#define IDC_STATIC_LABEL_SCALE_H        1500
#define IDC_STATIC_PERCENT_SCALE_H      1501
#define IDC_STATIC_LABEL_X_ANGLE        1502
#define IDC_STATIC_LABEL_Y_ANGLE        1503
#define IDC_STATIC_LABEL_X_ANGLE2       1504
#define IDC_STATIC_LABEL_ROTATION       1504
#define IDC_EDIT_BUTTON_TEXT            1507
#define IDC_TEXT_LIST                   1508
#define IDC_SOUND_LIST                  1509
#define IDC_SHAPE_LIST                  1510
#define IDC_BTN_PLAY_SOUND              1511
#define IDC_STATIC_TEXT_PREVIEW         1512
#define IDC_STATIC_ANGLE_LABEL          1513
#define IDC_STATIC_OFFSET_X_LABEL       1515
#define IDC_STATIC_FONT                 1515
#define IDC_STATIC_OFFSET_Y_LABEL       1516
#define IDC_STATIC_TEXT_WIDTH           1517
#define IDC_STATIC_RECT                 1518
#define IDC_STATIC_TEXT_HEIGHT          1518
#define IDC_EDIT_FRAMES                 1521
#define IDC_SPIN_FRAMES                 1525
#define IDC_LIST_EVENTS                 1526
#define IDC_STATIC_PLACEHOLDER          1527
#define IDC_DIR_TREE_CTRL               1528
#define IDC_BUTTON_REFRESH_DIR          1529
#define IDC_EDIT_TYPE                   1530
#define IDC_EDIT_LOCATION               1532
#define IDC_EDIT_CREATED_TIME           1534
#define IDC_EDIT_MODIFIED_TIME          1535
#define IDC_EDIT_ACCESSED_TIME          1536
#define IDC_EDIT_DIMENSIONS             1538
#define IDC_EDIT_DURATION               1539
#define IDC_STATIC_DURATION             1541
#define IDC_STATIC_DIMENSIONS           1542
#define IDC_TREE_EFFECTS                1544
#define IDC_STATIC_ADV_OPTIONS          1554
#define IDC_CHECK_USE_SELECTED          1555
#define IDC_STATIC_TEXT_STYLE_RECT      1556
#define IDC_BUTTON_CLEAR_ALL            1562
#define IDC_STATIC_LIST                 1563
#define IDC_STATIC_PLAYER               1564
#define IDC_CHECK_SHOW_AT_STARTUP       1565
#define IDC_BUTTON_EDIT_ACTION          1567
#define IDC_STATIC_FRAMES               1570
#define IDC_STATIC_TIME                 1571
#define IDC_STATIC_OBJECTS              1572
#define IDC_STATIC_SOUNDS               1573
#define IDC_STATIC_SCENES               1574
#define IDC_CHECK_SPECIFY_FRAMES        1575
#define IDC_STATIC_FRAME_START          1576
#define IDC_STATIC_TIME_START           1577
#define IDC_STATIC_FRAME_COUNT          1578
#define IDC_STATIC_TIME_LENGTH          1580
#define IDC_STATIC_S1                   1581
#define IDC_STATIC_S11                  1582
#define IDC_STATIC_S2                   1583
#define IDC_STATIC_S21                  1584
#define IDC_STATIC_S3                   1585
#define IDC_STATIC_S31                  1586
#define IDC_STATIC_S4                   1587
#define IDC_STATIC_S41                  1588
#define IDC_STATIC_STATISTICS           1589
#define IDC_EDIT_SAMPLE_RATE            1592
#define IDC_EDIT_SAMPLE_CHANNEL         1593
#define IDC_STATIC_SAMPLE_RATE          1596
#define IDC_STATIC_SAMPLE_CHANNEL       1597
#define IDC_COMBO_SOUND_LIST            1599
#define IDC_CHECK_CACHE_RESOURCES       1600
#define IDC_CHECK_SHOW_TOOLTIP          1601
#define IDC_RADIO_NORMAL                1602
#define IDC_CHECK_SHOW_TOOLTIP2         1602
#define IDC_CHECK_SHOW_ALL_ELEMENTS     1602
#define IDC_RADIO_BACKGROUND            1603
#define IDC_BUTTON_COMMENT              1603
#define IDC_EDIT_COMMENT                1604
#define IDC_BUTTON_STOP_SOUND           1605
#define IDC_SOUND_SLIDER                1606
#define IDC_PRO_BAR                     1607
#define IDC_STATIC_TIPS                 1608
#define IDC_CHECK_QUIT_FULLSCREEN_ON_ESC 1609
#define IDC_CHECK2                      1610
#define IDC_CHECK_CLOSE_PREVIEW_ON_ESC  1610
#define IDC_STATIC_FILL_TRANSFORM       1610
#define IDC_CHECK_AUTO_HIDE_BORDER      1611
#define IDC_CHECK_AUTO_HIDE_CAPTION     1611
#define IDC_RADIO_KEEP_CURRENT_SIZE     1611
#define IDC_RADIO_AUTO_CALCULATE        1612
#define IDC_RADIO_SPECIFY               1613
#define IDC_BTN_COLOR                   1617
#define IDC_BTN_BOLD                    1618
#define IDC_BTN_ITALIC                  1619
#define IDC_EDIT_SPACE                  1620
#define IDC_FLASH_PLAYER                1621
#define IDC_BTN_CONFIG                  1623
#define IDC_STATIC_SIZE                 1625
#define IDC_STATIC_SPACE                1626
#define IDC_STATIC_TEXT_TOOL            1627
#define IDC_DROP_EFFECT                 1628
#define IDC_LABEL_SPACE                 1630
#define IDC_LABEL_SIZE                  1631
#define IDC_STATIC_PREVIEW              1632
#define IDC_LABEL_URL                   1633
#define IDC_LABEL_TARGET                1636
#define IDC_LIST_TEMPLATE               1638
#define IDC_LIST_TEXTS                  1642
#define IDC_RADIO_KEEP_SIZE             1644
#define IDC_RADIO_KEEP_BOUND            1645
#define IDC_COMBO_POS                   1647
#define IDC_LIST_SCENE                  1648
#define IDC_STATIC_THUMBNAIL            1649
#define IDS_GS_SELECTRESOURCE           2000
#define IDC_TAB                         3003
#define IDD_GLD_PROPERTYSHEET           3005
#define IDC_CHECK_BREAK_APART           3008
#define IDD_PAGE_COMMON                 3008
#define IDC_CHECK_TEXT_BORDER           3009
#define IDC_EDIT_BORDER_WIDTH           3010
#define IDC_EDIT_SHADOW_SIZE            3011
#define IDC_SPIN_BORDER_WIDTH           3012
#define IDC_CHECK_CUSTOM_FILL           3013
#define IDC_EDIT_ANGLE                  3014
#define IDC_CHECK_FILL_INDIVIDUALLY     3015
#define IDC_CHECK_ADD_SHADOW            3016
#define IDB_LAYOUT_ALIGN_BOTTOM         4058
#define IDB_LAYOUT_ALIGN_TOP            4060
#define IDB_LAYOUT_ALIGN_MIDDLE         4063
#define IDB_LAYOUT_SIZE_WIDTH           4064
#define IDB_LAYOUT_SIZE_HEIGHT          4065
#define IDB_LAYOUT_SIZE_BOTH            4066
#define IDB_LAYOUT_SPACE_ACROSS         4068
#define IDB_LAYOUT_SPACE_DOWN           4069
#define IDC_EDIT_WIDTH                  4073
#define IDC_EDIT_HEIGHT                 4076
#define IDD_COLOR_SWATCH                4079
#define IDD_UNDO                        4083
#define IDD_BROWSERS                    4084
#define IDC_BUTTON_ADD_TO_SWATCH        4088
#define IDC_BUTTON_PARENT_DIR           4088
#define IDC_BUTTON_BACK                 4089
#define IDC_BUTTON_FORWARD              4090
#define IDC_BUTTON_STOCK_RESOURCES      4091
#define IDC_BUTTON_HOME_DIR             4092
#define IDC_BUTTON_GOTO_FOLDER          4093
#define IDC_COMBO_QUALITY               4096
#define IDC_COMBO_WMODE                 4097
#define IDC_COMBO_HTML_ALIGN            4098
#define IDC_COMBO_SCALE                 4099
#define IDC_COMBO_FLASH_ALIGN           4100
#define IDC_CHECK_PAUSE                 4103
#define IDC_CHECK_MENU                  4104
#define IDC_CHECK_DEVICEFONT            4106
#define IDB_COLOR_PALETTE               4107
#define IDD_ABOUTBOX                    4127
#define IDD_EFFECT_PANEL                4144
#define IDD_TOOL_OPTION_ROUND_RECT_TOOL 4147
#define IDD_PREVIEW                     4148
#define IDD_PROGRESS                    4149
#define IDD_INPUTBOX                    4154
#define IDD_TOOL_OPTION_POLYGON_TOOL    4155
#define IDD_TOOL_OPTION_STAR_TOOL       4156
#define IDD_OPTIONS_GENERAL             4157
#define IDD_OPTIONS_DESIGN              4158
#define IDD_OPTIONS_TIMELINE            4160
#define IDD_CHECK_MESSAGE_BOX           4166
#define IDD_SELECT_TARGET               4167
#define IDD_PUBLISH_EXPORT              4169
#define IDD_PUBLISH_FINISHED            4170
#define IDD_PUBLISH_SELECT_HTML         4171
#define IDD_PUBLISH_HTML_OPTIONS        4172
#define IDD_PUBLISH_VIEW_CODE           4173
#define IDD_PUBLISH_INSERT_CODE         4174
#define IDD_OPTIONS_PREVIEW             4175
#define IDD_OPTIONS_AS                  4182
#define IDD_TEMPLATES                   4186
#define IDD_TEMPLATE                    4190
#define IDD_INSTANCE_ACTION             4191
#define IDD_MOVIE_PROPERTIES            4192
#define IDD_EDIT_SHAPE_FILL_PAGE        4193
#define IDD_EDIT_MATRIX_PAGE            4194
#define IDD_EDIT_CXFORM_PAGE            4195
#define IDD_EDIT_SHAPE_LINE_PAGE        4198
#define IDD_TOOL_OPTION_TEXT_TOOL       4201
#define IDD_EDIT_MC_TEXT_PAGE           4204
#define IDD_EDIT_MC_SHAPE_PAGE          4205
#define IDD_EDIT_MC_SOUND_PAGE          4206
#define IDD_EDIT_MC_EDIT_TEXT_DIALOG    4207
#define IDD_EDIT_MC_REPLACE_DIALOG      4208
#define IDD_EDIT_GENERAL_PAGE           4209
#define IDD_RESOURCE_EXPLORER_WND       4210
#define IDD_SCENE_PROPERTIES_PAGE       4212
#define IDD_SCENE_ACTION                4213
#define IDD_SCENE_ACTION_PAGE           4214
#define IDD_RESOURCE_THUMB_OBJ_PROPERTIES 4215
#define IDD_INSTANCE_ACTION_PAGE        4216
#define IDD_MOVIE_SOUND                 4217
#define IDD_COMMENT                     4218
#define IDD_FONT_PREVIEW                4219
#define IDB_BOLD                        4363
#define IDB_DOWN                        4371
#define IDB_FLOATER_MENU                4372
#define IDB_RIGHT                       4373
#define IDB_LEFT                        4374
#define IDB_TOOL_RECT                   4375
#define IDB_TOOL_RESHAPE                4376
#define IDB_TOOL_LINE                   4377
#define IDB_TOOL_TEXT                   4378
#define IDB_TOOL_OVAL                   4379
#define IDB_TOOL_PENCIL                 4380
#define IDB_TOOL_PEN                    4381
#define IDB_TOOL_INK_BOTTLE             4382
#define IDB_TOOL_PAINT_BUCKET           4383
#define IDB_LINE                        4384
#define IDB_FILL                        4385
#define IDB_TOOL_FILL_TRANSFORM         4386
#define IDB_SYMBOLS                     4387
#define IDB_CONSTRAIN_LINK              4388
#define IDB_DEGREE                      4389
#define IDB_BUTTON_BROWSE               4390
#define IDB_BUTTON_PLAY                 4391
#define IDB_NAV_BAR                     4392
#define IDB_MENU_CHECK                  4393
#define IDB_TOOL_ROUND_RECT             4394
#define IDB_TOOL_POLYGON                4395
#define IDB_TOOL_STAR                   4396
#define IDB_BUTTON_STOP                 4397
#define IDB_CHAR_SPACING                4398
#define IDB_LINE_SPACING                4399
#define IDB_ALIGN_LEFT                  4400
#define IDB_ALIGN_RIGHT                 4401
#define IDB_ALIGN_CENTER                4402
#define IDB_BUTTON_SELECTABLE           4403
#define IDB_BUTTON_EDITABLE             4404
#define IDB_BUTTON_BORDER               4405
#define IDB_INDENT                      4406
#define IDB_LEFT_MARGIN                 4407
#define IDB_RIGHT_MARGIN                4408
#define IDB_RADIUS                      4411
#define IDB_POINTS                      4412
#define IDB_CHAR_POS                    4413
#define IDB_LAYOUT_SEND_TO_BACK         4414
#define IDB_LAYOUT_BRING_TO_FRONT       4415
#define IDB_BUTTON_DELETE               4416
#define IDB_MOVIECLIP                   4417
#define IDB_ADD_EVENT                   4418
#define IDB_ADD_ACTION                  4419
#define IDB_BUTTON_UP                   4420
#define IDB_BUTTON_DOWN                 4421
#define IDB_LINK                        4422
#define IDB_LAYOUT_BRING_FORWARD        4423
#define IDB_LAYOUT_SEND_BACKWARD        4424
#define IDB_BALLOONTOOLTIP              4425
#define IDB_BUTTON_TARGET               4426
#define IDB_BUTTON_CHECK_SYNTAX         4427
#define IDB_BUTTON_ACTION               4428
#define IDB_BUTTON_REFRESH              4429
#define IDB_BUTTON_FILTER               4430
#define IDB_BUTTON_LAYER                4431
#define IDB_BUTTON_FRAMECLIP            4432
#define IDB_BUTTON_MOVIECLIP            4433
#define IDB_BUTTON_BUTTON               4434
#define IDB_BUTTON_GRAPHIC              4435
#define IDB_BUTTON_TEXT                 4436
#define IDB_BUTTON_EFFECT               4437
#define IDB_FIND                        4438
#define IDB_BUTTON_PARAMETER_INFO       4439
#define IDB_BUTTON_AUTO_COMPLETE        4440
#define IDB_EFFWND_SOUND_LIST           4441
#define IDB_EFFECT_DEFAULT              4442
#define IDB_EFFWND_EXPANDED_ICON        4444
#define IDB_BUTTON_EFFECT_ADD           4445
#define IDB_BUTTON_EFFECT_CONFIG        4446
#define IDB_EVENTS                      4447
#define IDB_EFFWND_EFFECT_TOTAL         4448
#define IDB_BUTTON_CLOSE2               4449
#define IDB_POPUP                       4450
#define IDB_BLANK_DOC                   4451
#define IDB_ADD_SOUND                   4452
#define IDS_EDIT_BUTTON_SHEET_CAPTION   8000
#define IDS_EDIT_BUTTON_PAGE_UP_CAPTION 8001
#define IDS_EDIT_BUTTON_PAGE_OVER_CAPTION 8002
#define IDS_EDIT_BUTTON_PAGE_DOWN_CAPTION 8003
#define IDS_EDIT_BUTTON_PAGE_HIT_CAPTION 8004
#define IDS_BUTTON_STATUS_FULL          8005
#define IDS_PANEL_CAPTION_IMAGE         8006
#define IDS_PANEL_CAPTION_SHAPE         8007
#define IDS_PANEL_CAPTION_BUTTON        8008
#define IDS_EDIT_SHAPE_SHEET_CAPTION    8009
#define IDS_EDIT_SPRITE_SHEET_CAPTION   8010
#define IDS_EDIT_TEXT_SHEET_CAPTION     8011
#define IDS_EDIT_MC_REPLACE_IMAGE_DIALOG_CAPTION 8012
#define IDS_EDIT_MC_REPLACE_SHAPE_DIALOG_CAPTION 8013
#define IDS_EDIT_MC_REPLACE_BUTTON_DIALOG_CAPTION 8014
#define IDS_EDIT_MC_REPLACE_SOUND_DIALOG_CAPTION 8015
#define IDS_MOVIE_CLIP_STATUS_TEXT      8016
#define IDS_SCENE_SOUND_CAPTION         8017
#define IDS_THUMB_TIP_IMAGE             8018
#define IDS_THUMB_TIP_SHAPE             8019
#define IDS_THUMB_TIP_BUTTON            8020
#define IDS_THUMB_TIP_SOUND             8021
#define IDS_BUTTON_UNNAMED_PREFIX_TEXT  8023
#define IDS_BUTTON_UNNAMED_PREFIX_SHAPE 8024
#define IDS_BUTTON_UNNAMED_PREFIX_SOUND 8025
#define IDS_THUMB_TIP_UNNAMED_IMAGE_OBJ 8026
#define IDS_THUMB_TIP_UNNAMED_SHAPE_OBJ 8027
#define IDS_THUMB_TIP_UNNAMED_BUTTON_OBJ 8028
#define IDS_THUMB_TIP_UNNAMED_SOUND_OBJ 8029
#define IDS_PANEL_CAPTION_SOUND         8030
#define IDS_STOCK_RESOURCES_TREE_ITEM_TEXT 8031
#define IDS_PROMPT_NONE_RESOURCE_SELECTED 8032
#define IDS_CATEGORY_TAB_RESOURCE_CAPTION 8033
#define IDS_CATEGORY_TAB_IMPORT_CAPTION 8034
#define IDS_CATEGORY_TAB_TOOLS_CAPTION  8035
#define IDS_BUTTON_TIP_GOTO_FOLDER      8036
#define IDS_RESOURCE_GLS_FORMAT         8037
#define IDS_RESOURCE_GLB_FORMAT         8038
#define IDS_RESOURCE_BMP_FORMAT         8039
#define IDS_RESOURCE_PNG_FORMAT         8040
#define IDS_RESOURCE_JPG_FORMAT         8041
#define IDS_RESOURCE_MP3_FORMAT         8042
#define IDS_RESOURCE_WAV_FORMAT         8043
#define IDS_RESOURCE_METAFILE_FORMAT    8044
#define IDS_RESOURCE_OBJ_IMAGE          8045
#define IDS_RESOURCE_OBJ_SHAPE          8046
#define IDS_RESOURCE_OBJ_BUTTON         8047
#define IDS_RESOURCE_OBJ_SOUND          8048
#define IDS_ERROR_CHANGE_FILE_NAME_EXTENSION 8049
#define IDS_ERROR_INVALID_FILE_NAME     8050
#define IDS_FOLDER_NOT_FOUND            8051
#define IDS_E_INVALID_INSTANCE_NAME     8052
#define IDS_EDIT_INSTANCE_SHEET_CAPTION 8053
#define IDS_ERROR_FILE_NOT_EXIST1       8054
#define IDS_SELECT_SOUND_TITLE          8055
#define IDS_EDIT_MC_SHAPE_SHEET_CAPTION 8056
#define IDS_PANEL_CAPTION_MOVIECLIP     8057
#define IDS_EDIT_MC_REPLACE_MOVIECLIP_DIALOG_CAPTION 8058
#define IDS_RESOURCE_GLM_FORMAT         8059
#define IDS_THUMB_TIP_UNNAMED_MOVIECLIP_OBJ 8060
#define IDS_BTN_CONFIG_CAPTION          8061
#define IDS_BTN_INFO_CAPTION            8062
#define IDS_MOVIE_SOUND_NONE            8063
#define IDS_MOVIE_SOUND_UNNAMED         8064
#define IDS_BTN_PLAY_SOUND              8065
#define IDS_BTN_STOP_SOUND              8066
#define IDS_SAMPLE_CHANNEL_MONO         8067
#define IDS_SAMPLE_CHANNEL_STERO        8068
#define IDS_PROMPT_ADD_ANIMATED_EFFECTS 8069
#define IDS_INPUT_TEXT_HERE             8070
#define IDC_DRAG_SINGLE_COPY            16080
#define IDC_DRAG_MULTIPLE_COPY          16081
#define IDC_DRAG_MULTIPLE               16083
#define IDC_HAND_HOLD                   18310
#define IDC_HAND_DRAG                   18311
#define _ID_CUSTOMIZE                   32773
#define _ID_RESET                       32774
#define ID_PLAYER_ZOOMIN                32775
#define ID_PLAYER_ZOOMOUT               32776
#define ID_PLAYER_QUALITY_LOW           32779
#define ID_PLAYER_QUALITY_MEDIUM        32780
#define ID_PLAYER_QUALITY_HIGH          32781
#define ID_PLAYER_SHOWALL               32782
#define ID_FILE_PUBLISH                 32784
#define ID_FILE_PREVIEW                 32798
#define ID_VIEW_SOUND                   32956
#define ID_VIEW_TRANSFORM               32957
#define ID_VIEW_TEXT                    32958
#define ID_VIEW_ACTION                  32959
#define ID_VIEW_LIBRARY                 32960
#define ID_FILE_EXPORT_MOVIE            32961
#define ID_FILE_NEW_WINDOW              32962
#define ID_FORMAT_ALIGNLEFTS            32973
#define ID_FORMAT_ALIGNTOPS             32974
#define ID_FORMAT_ALIGNRIGHTS           32975
#define ID_FORMAT_ALIGNBOTTOMS          32976
#define ID_FORMAT_ALIGNCENTERS          32977
#define ID_FORMAT_ALIGNMIDDLES          32978
#define ID_FORMAT_MAKESAMEHEIGHT        32980
#define ID_FORMAT_MAKESAMESIZE          32981
#define ID_FORMAT_MAKESAMEWIDTH         32982
#define ID_FORMAT_MAKEHORIZONTALSPACINGEQUAL 32983
#define ID_FORMAT_MAKEVERTICALSPACINGEQUAL 32984
#define ID_FORMAT_BRINGTOFRONT          32985
#define ID_FORMAT_SENDTOBACK            32986
#define ID_CONVERT_SYMBOL               32988
#define ID_EDIT_GROUP                   32991
#define ID_EDIT_BREAKAPART              32992
#define ID_VIEW_TOOLS                   32993
#define ID_VIEW_LAYOUT                  32995
#define ID_FORMAT_BRINGFORWARD          33007
#define ID_FORMAT_SENDBACKWARD          33008
#define ID_CONVERT_TO_KEYFRAME          33046
#define ID_CONVERT_TO_BLANK_KEYFRAME    33047
#define ID_EDIT_UNGROUP                 33065
#define ID_EDIT_INSTANCE                33066
#define ID_TEXT_UNDO                    33070
#define ID_TEXT_REDO                    33071
#define ID_TEXT_DELETEBACK              33073
#define ID_TEXT_GOTO_BEGIN_OF_TEXT      33081
#define ID_TEXT_GOTO_END_OF_TEXT        -32453
#define ID_INSERT_NEWSYMBOL             33089
#define ID_VIEW_CUSTOMIZETOOLBAR        33094
#define ID_DEBUG_TESTIMPORT             33095
#define ID_LOCATE_SYMBOL                33097
#define ID_HELP_TUTORIAL                33098
#define ID_GRID_SHOWGRID                33100
#define ID_GRID_EDITGRID                33101
#define ID_GRID_SNAPTOGRID              33102
#define ID_FILE_FAST_EXPORT_MOVIE       33113
#define ID_VIEW_OUTPUT                  33119
#define ID_SWITCH_WINDOW                33142
#define ID_VIEW_RULERS                  33145
#define ID_EDIT_REFERENCE               33155
#define ID_EDIT_COMPLETE_WORD           33165
#define ID_SOUND_PLAY                   33173
#define ID_SOUND_DELETE                 33174
#define ID_SOUND_VIEW_FRAMES            33176
#define ID_SOUND_IMPORT                 33178
#define ID_VIEW_ZOOMIN                  33185
#define ID_VIEW_ZOOMOUT                 33186
#define ID_SWAP_SYMBOL                  33190
#define ID_FILE_IMPORT_TO_LIB           33198
#define ID_HELP_REGISTER                33202
#define ID_SCENE_RENAME                 33208
#define ID_SCENE_ADD                    33209
#define ID_SCENE_INSERT                 33211
#define ID_EDIT_MOVIE_PROPERTIES        33219
#define ID_FILE_NEW_FROM_TEMPLATE       33221
#define ID_EDIT_ACTIONSCRIPT            33224
#define ID_EDIT_INSTANCE_ACTIONSCRIPT   33228
#define ID_EDIT_SCENE_ACTIONSCRIPT      33229
#define ID_EDIT_INSTANCE_PROPERTIES     33230
#define ID_VIEW_ZOOM                    33235
#define ID_INSERT_EFFECTS               33244
#define ID_INSERT_SCENE                 33245
#define ID_INSERT_SOUND                 33246
#define ID_GOTO_HOME_DIRECTORY          33258
#define ID_GOTO_STOCK_RESOURCES         33259
#define ID_GOTO_DESKTOP                 33261
#define ID_GOTO_MY_DOCUMENTS            33262
#define ID_GOTO_MY_COMPUTER             33263
#define ID_GOTO_NETWORK_PLACE           33264
#define ID_RESOURCE_TREE_EXPLORE        33270
#define ID_RESOURCE_TREE_REFRESH        33271
#define ID_THUMB_PLAY_SOUND             33283
#define ID_THUMB_COPY                   33284
#define ID_THUMB_DELETE                 33285
#define ID_THUMB_RENAME                 33286
#define ID_THUMB_EXPLORE                33287
#define ID_THUMB_PROPERTIES             33288
#define ID_FILE_EXPORTRESOURCE          33294
#define ID_VIEW_SCENES                  33297
#define ID_EDIT_SCENE_PROPERTIES        33298
#define ID_TEXT_STYLE_SAVE_STYLE        33302
#define ID_VIEW_FILES                   33303
#define ID_VIEW_RESOURCE                33304
#define ID_EFFECT_ADD                   33306
#define ID_TEXT_STYLE_APPLY_STYLE       33309
#define ID_TIME_LINE_MOVE_UP            33324
#define ID_TIME_LINE_CONFIG             33326
#define ID_TIME_LINE_PLAY_SOUND         33327
#define ID_TIME_LINE_MOVE_DOWN          33328
#define ID_TIME_LINE_SOUND_INFO         33329
#define ID_HELP_ABOUT_LAME              33335
#define ID_INSERT_IMAGE                 33337
#define ID_THUMB_ADD_TO_SCENE           33340
#define ID_PREVIEW_ESCAPE               33342
#define ID_EDIT_PREV_INSTANCE           33344
#define ID_EDIT_NEXT_INSTANCE           33345
#define ID_VIEW_SHOW_ALL_INSTANCES      33350
#define ID_TIME_LINE_CUT                33351
#define ID_TIME_LINE_COPY               33352
#define ID_TIME_LINE_PASTE              33353
#define ID_TIME_LINE_REMOVE             33354
#define ID_INSERT_TEXT                  33355
#define ID_ELEMENT_APPLYMODE            33362
#define ID_ELEMENT_SAVEASMODE           33363
#define ID_ELEMENT_SAVEASTEMPLATE       33364
#define ID_ELEMENT_APPLYTEMPLATE        33365
#define ID_CHANGE_BUTTON_TEXT           33369
#define ID_TIMELINE_REPLACE             33370
#define ID__SERVERASBACKGROUND          33371
#define ID_SERVERASBACKGROUND_STRETCH   33372
#define ID_SERVERASBACKGROUND_CENTER    33373
#define ID_SERVERASBACKGROUND_CURRENT   33374
#define ID__DUPLICATESCENE              33375
#define ID__BACKGROUND                  33376
#define ID_BACKGROUND_TAKEOUT           33377
#define ID_BACKGROUND_CENTERED          33379
#define ID_BACKGROUND_STRETCHED         33380
#define ID_BACKGROUND_EMPTY             33381
#define ID__SETASBACKGROUND             33382
#define ID__CHANGEBACKGROUND            33383
#define ID_SETASBACKGROUND              33386
#define ID_CHANGEBACKGROUND             33387
#define ID_CHANGEBACKGROUND_EMPTY       33388
#define ID_CHANGEBACKGROUND_RESTORE     33389
#define ID_CHANGEBACKGROUND_POSITION    33390
#define ID_TOOLS_TEST                   33391
#define ID_PREVIEW_BROWSER1             34001
#define ID_PREVIEW_BROWSER99            34099
#define ID_MY_RECENT_FILES              34100
#define ID_MY_RECENT_FILES9             34109
#define ID_EDIT_LIST_MEMBERS            37904
#define ID_EDIT_PARAMETER_INFO          37905
#define IDS_ENTER_BROWSER_NAME          40001
#define IDS_E_INVALID_DIRECTORY_NAME    50000
#define IDS_PROMPT_CREATE_DIRECTORY1    50001
#define IDS_E_CREATE_DIRECTORY1         50002
#define IDS_ACTION_UNDO_ACTION          60001
#define IDS_ACTION_REDO_ACTION          60002
#define IDS_ACTION_UNDO_ACTIONS1        60003
#define IDS_ACTION_REDO_ACTIONS1        60004
#define IDS_INVALID_FOLDER_NAME         63017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        450
#define _APS_NEXT_COMMAND_VALUE         33392
#define _APS_NEXT_CONTROL_VALUE         1650
#define _APS_NEXT_SYMED_VALUE           427
#endif
#endif
